version: "2"
volumes:
  workdir:
services:
  downloader:
    build: .
    privileged: true
    ports:
      - 3000:3000
    volumes:
      - "workdir:/usr/src/app/update_live" # shared workdir for other services
    labels:
      io.resin.features.dbus: "1"
      io.resin.features.kernel-modules: "1"
      io.resin.features.firmware: "1"
      io.balena.features.supervisor-api: "1"
